import ItemTypes from '../layouts/ItemTypes';
import {
  A1,
  A10,
  A11,
  A12,
  A13,
  A14,
  A15,
  A16,
  A17,
  A18,
  A19,
  A2,
  A20,
  A21,
  A3,
  A4,
  A5,
  A6,
  A7,
  A8,
  A9,
  A5801,
  A5802,
  A5803,
} from '../components/ADragComponents';
import { B1, B10, B2, B3, B4, B5, B6, B7, B8, B9, B5801 } from '../components/BDragComponents';

export const ABOXES = [
  {
    id: '1',
    componentName: 'A1',
    name: '待初审',
    ChartId: '1',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '2',
    componentName: 'A2',
    name: '待复审',
    ChartId: '2',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '3',
    componentName: 'A3',
    name: '上传成功',
    ChartId: '3',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '4',
    componentName: 'A4',
    name: '异常数据',
    ChartId: '4',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '5',
    componentName: 'A5',
    name: '重点企业总数',
    ChartId: '10',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '6',
    componentName: 'A6',
    name: '重点车辆总数',
    ChartId: '11',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '7',
    componentName: 'A7',
    name: '驾驶人总数',
    ChartId: '12',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '8',
    componentName: 'A8',
    name: '预警总数',
    ChartId: '13',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '9',
    componentName: 'A9',
    name: '本日任务完成数',
    ChartId: '14',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '10',
    componentName: 'A10',
    name: '本日巡检总量',
    ChartId: '15',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '11',
    componentName: 'A11',
    name: '自动研判警情数',
    ChartId: '16',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '12',
    componentName: 'A12',
    name: '警情待审核数',
    ChartId: 17,
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '13',
    componentName: 'A13',
    name: '警情上报总数',
    ChartId: 18,
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '14',
    componentName: 'A14',
    name: '巡检警情发现总量',
    ChartId: '19',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '15',
    componentName: 'A15',
    name: '执勤警力总数',
    ChartId: '20',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '16',
    componentName: 'A16',
    name: '本日简易处罚数量',
    ChartId: '21',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '17',
    componentName: 'A17',
    name: '本日强制措施数量',
    ChartId: '22',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '18',
    componentName: 'A18',
    name: '本月新增申请数',
    ChartId: '23',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '18',
    componentName: 'A18',
    name: '本月新增申请数',
    ChartId: '23',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '19',
    componentName: 'A19',
    name: '待审批总数',
    ChartId: '24',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '20',
    componentName: 'A20',
    name: '施工中数',
    ChartId: '25',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },

  {
    id: '21',
    componentName: 'A5801',
    name: '待审核警情数',
    ChartId: '27',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '22',
    componentName: 'A5802',
    name: '视频巡检总量',
    ChartId: '28',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
  {
    id: '23',
    componentName: 'A5803',
    name: '警情上报数',
    ChartId: '29',
    type: ItemTypes.AWORKBENCH,
    nsize: 1,
    parameterconfig: null,
  },
];

export const BBOXES = [
  {
    id: '1',
    componentName: 'B1',
    name: '日常数据统计',
    ChartId: '5',
    type: ItemTypes.BWORKBENCH,
    nsize: '1',
    parameterconfig: null,
  },
  {
    id: '2',
    componentName: 'B2',
    name: '违章数据源',
    ChartId: '6',
    type: ItemTypes.BWORKBENCH,
    nsize: '1',
    parameterconfig: null,
  },
  {
    id: '3',
    componentName: 'B3',
    name: '待办事项',
    ChartId: '7',
    type: ItemTypes.BWORKBENCH,
    nsize: '1',
    parameterconfig: null,
  },
  {
    id: '4',
    componentName: 'B4',
    name: '事故数量统计',
    ChartId: '8',
    type: ItemTypes.BWORKBENCH,
    nsize: '1',
    parameterconfig: null,
  },
  {
    id: '5',
    componentName: 'B5',
    name: '公告',
    ChartId: '9',
    type: ItemTypes.BWORKBENCH,
    nsize: '1',
    parameterconfig: null,
  },
  {
    id: '6',
    componentName: 'B6',
    name: '巡检员工作量',
    ChartId: '27',
    type: ItemTypes.BWORKBENCH,
    nsize: '1',
    parameterconfig: null,
  },
  {
    id: '7',
    componentName: 'B7',
    name: '警情类型分析',
    ChartId: '28',
    type: ItemTypes.BWORKBENCH,
    nsize: '1',
    parameterconfig: null,
  },
  {
    id: '8',
    componentName: 'B8',
    name: '警情来源分析',
    ChartId: '29',
    type: ItemTypes.BWORKBENCH,
    nsize: '1',
    parameterconfig: null,
  },
  {
    id: '9',
    componentName: 'B9',
    name: '警情时段分析',
    ChartId: '30',
    type: ItemTypes.BWORKBENCH,
    nsize: '1',
    parameterconfig: null,
  },
  {
    id: '10',
    componentName: 'B10',
    name: '占路施工申请趋势',
    ChartId: '31',
    type: ItemTypes.BWORKBENCH,
    nsize: '1',
    parameterconfig: null,
  },
  {
    id: '11',
    componentName: 'B5801',
    name: '警情审核数据统计',
    ChartId: '32',
    type: ItemTypes.BWORKBENCH,
    nsize: '1',
    parameterconfig: null,
  },
];

export const dragcomponents4A = {
  1: A1,
  2: A2,
  3: A3,
  4: A4,
  10: A5,
  11: A6,
  12: A7,
  13: A8,
  14: A9,
  15: A10,
  16: A11,
  17: A12,
  18: A13,
  19: A14,
  20: A15,
  21: A16,
  22: A17,
  23: A18,
  24: A19,
  25: A20,
  26: A21,
  27: A5801,
  28: A5802,
  29: A5803,
};

export const dragcomponentsB = {
  5: B1,
  6: B2,
  7: B3,
  8: B4,
  9: B5,
  27: B6,
  28: B7,
  29: B8,
  30: B9,
  31: B10,
  32: B5801,
};

export const THEMES = {
  dark: '1',
  light: '2',
};
